version: 2.1
orbs:
  node: circleci/node@4.1.0

defaults: &defaults
  working_directory: ~/repo
  executor: 
    name: node/default
    tag: '16.0'
  resource_class: large

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: yarn install
      - run:
          name: Run tests
          command: yarn test
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: ~/repo
          paths: .
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Build site
          command: CI="" yarn build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - public
            - deployment
  publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: sudo yarn global add aws-cdk@1.94.1
      - run: CI="" cd deployment && yarn install && yarn build
      - run:
          name: Publish site
          command: cd deployment && cdk bootstrap --force && cdk deploy --progress events --ci --require-approval never

workflows:
  main:
    when:
      not:
        equal: [api, << pipeline.trigger_source >>]
    jobs:
      - test:
          filters:
            branches:
              only:
                - develop
                - main
      - build:
          requires:
            - test
          filters:
            branches:
              only:
                - main
      - publish:
          requires:
            - build
          filters:
            branches:
              only:
                - main
  cms:
    when:
      equal: [api, << pipeline.trigger_source >>]
    jobs:
      - deploy-approval:
          type: approval
          filters:
            branches:
              only:
                - main
      - test:
          requires:
            - deploy-approval
      - build:
          requires:
            - test
      - publish:
          requires:
            - build
